name: Languages activity
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  # push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:  
      - name: Custom
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_SUDO_TOKEN }}
          filename: images/metrics.plugin.languages.custom.svg
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: Gunārs Ābeltiņš, GunarsA, gunars2003@gmail.com
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: lines, bytes-size
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15
          plugin_languages_skipped: GunarsA/CultureGenerator,GunarsA/LU-TT1-Md3
          
      - name: Custom 2
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: images/metrics.plugin.languages.custom2.svg
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: Gunārs Ābeltiņš, GunarsA, gunars2003@gmail.com
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: lines, bytes-size
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15
          plugin_languages_skipped: GunarsA/CultureGenerator,GunarsA/LU-TT1-Md3
          
#       - name: Indepth analysis
#         uses: lowlighter/metrics@latest
#         with:
#           filename: metrics.plugin.languages.indepth.svg
#           token: ${{ secrets.METRICS_SUDO_TOKEN }}
#           base: ""
#           plugin_languages: yes
#           plugin_languages_ignored: >-
#             html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
#             gnuplot
#           plugin_languages_indepth: yes
#           plugin_languages_details: lines, bytes-size
#           plugin_languages_limit: 4
#           plugin_languages_analysis_timeout: 15
