name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  # push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_SUDO_TOKEN }}
          
#       - name: Mildly interesting facts
#         uses: lowlighter/metrics@latest
#         with:
#           filename: metrics.plugin.habits.facts.svg
#           token: ${{ secrets.METRICS_TOKEN }}
#           base: ""
#           plugin_habits: yes
#           plugin_habits_facts: yes
#           plugin_habits_charts: no
#           config_timezone: Europe/Riga
#       - name: Recent activity charts
#         uses: lowlighter/metrics@latest
#         with:
#           filename: metrics.plugin.habits.charts.svg
#           token: ${{ secrets.METRICS_TOKEN }}
#           base: ""
#           plugin_habits: yes
#           plugin_habits_facts: no
#           plugin_habits_charts: yes
#           config_timezone: Europe/Riga
      
#       - name: GitHub Skyline
#         uses: lowlighter/metrics@latest
#         with:
#           filename: metrics.plugin.skyline.svg
#           token: NOT_NEEDED
#           base: ""
#           plugin_skyline: yes
#           plugin_skyline_year: 2022
          
#       - name: Full history calendar
#         uses: lowlighter/metrics@latest
#         with:
#           filename: metrics.plugin.calendar.full.svg
#           token: ${{ secrets.METRICS_TOKEN }}
#           base: ""
#           plugin_calendar: yes
#           plugin_calendar_limit: 0
